### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by PigYrj** [LinkinStars/springBootTemplate#1]
大佬问一下 你这篇博客左下角的人物是怎么实现的
https://www.cnblogs.com/linkstar/p/8412975.html

**Comment by LinkinStars** [comment]
将下面这段添加到博客园的页首html即可。。下次这种问题私信就好，提issue好尴尬。。。


<script type="text/javascript" charset="utf-8" async="" src="https://cdn.jsdelivr.net/npm/live2d-widget@3.1.4/lib/L2Dwidget.min.js"></script>

<script type="text/javascript">
setTimeout(() => {
        L2Dwidget.init({
                "model": {
                        "scale": 1
                },
                "display": {
                        "position": "left",
                        "width": 180,
                        "height": 260,
                        "hOffset": 0,
                        "vOffset": -20
                },
                "mobile": {
                        "show": false
                },
                "react": {
                        "opacityDefault": 0.7,
                        "opacityOnHover": 0.2
                }
        });
}, 1000)
</script>
